---
archives:
- name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
  format: zip
builds:
- binary: bootstrap
  main: cmd/aws-waf-log-extractor/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
release:
  prerelease: true
